    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?=APP::config('nazivAPP') ?></title>
    <link rel="stylesheet" href="<?=APP::config('url') ?>public/assets/css/foundation.css">
    <link rel="stylesheet" href="<?=APP::config('url') ?>public/assets/css/style.css">
    <link rel="stylesheet" href="<?=APP::config('url') ?>public/assets/css/login.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css">
    <link rel="apple-touch-icon" sizes="180x180" href="<?=APP::config('url') ?>public/favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="<?=APP::config('url') ?>public/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="<?=APP::config('url') ?>public/favicon/favicon-16x16.png">
    <link rel="manifest" href="<?=APP::config('url') ?>public/favicon/site.webmanifest">
    <link rel="mask-icon" href="<?=APP::config('url') ?>public/favicon/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">

