    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?=APP::config('nazivAPP') ?></title>
    <link rel="stylesheet" href="<?=APP::config('url') ?>public/assets/css/foundation.css">
    <link rel="stylesheet" href="<?=APP::config('url') ?>public/assets/css/style.css">
    <link rel="stylesheet" href="<?=APP::config('url') ?>public/assets/css/login.css">