<nav class="top-bar topbar-responsive">
  <div class="top-bar-title">
    <span data-responsive-toggle="topbar-responsive" data-hide-for="medium">
      <button class="menu-icon" type="button" data-toggle></button>
    </span>
    <a class="topbar-responsive-logo" href="<?=APP::config('url') ?>"><strong><?=APP::config('nazivAPP') ?></strong></a>
  </div>
  <div id="topbar-responsive" class="topbar-responsive-links">
    <div class="top-bar-right">
      <ul class="menu simple vertical medium-horizontal">
        <?php if(isset($_SESSION['autoriziran'])):?>
          <!-- ovdje dođe privatni dio izbornika -->
        <?php endif; ?>

        <li><a href="<?=APP::config('url') ?>index/onama"><button type="button" class="button hollow topbar-responsive-button">O nama</button></a></li>
        <?php if(!isset($_SESSION['autoriziran'])):?>
          <li><a href="<?=APP::config('url') ?>index/login"><button type="button" class="button hollow topbar-responsive-button">Login</button></a></li>
        <?php else: ?>
          <li><button type="button" class="button hollow topbar-responsive-button">Logout</button></li>
        <?php endif; ?>
      </ul>
    </div>
  </div>
</nav>

