<nav class="top-bar topbar-responsive">
  <div class="top-bar-title">
    <span data-responsive-toggle="topbar-responsive" data-hide-for="medium">
      <button class="menu-icon" type="button" data-toggle></button>
    </span>
    <a class="topbar-responsive-logo" href="#"><strong><?=APP::config('nazivAPP') ?></strong></a>
  </div>
  <div id="topbar-responsive" class="topbar-responsive-links">
    <div class="top-bar-right">
      <ul class="menu simple vertical medium-horizontal">   
        <li><button type="button" class="button hollow topbar-responsive-button">Onama</button></li>
        <li><button type="button" class="button hollow topbar-responsive-button">Login</button></li>
      </ul>
    </div>
  </div>
</nav>

