
    <div class="grid-x">
        <div class="large-12 small-12 cell">
            <div class="callout"
             <?php 
            if(App::config('dev')){
                echo 'style="background-color:red;"';
            }else{
                echo 'style="background-color:silver;"';
            }
             ?>>

            &copy; <?=APP::config('nazivAPP') ?> <?php echo date("Y"); ?>
            <?php 
            if(App::config('ip')){
                echo '(Rad lokalno)';
            }else{
                echo '(Rad u produkciji)';
            }
            ?>
            </div> 
        </div> 
    </div>
