<script src="<?=APP::config('url') ?>public/assets/js/vendor.js"></script>
<script src="<?=APP::config('url') ?>public/assets/js/foundation.js"></script>
<script src="<?=APP::config('url') ?>public/app.js"></script>
<script src="https://kit.fontawesome.com/c867b674eb.js" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>
<script>
$(document).ready(function() {
    var table = $('#example').DataTable();
     
    $('#example tbody').on('click', 'tr', function () {
        var data = table.row( this ).data();
        alert( 'Odabrali ste  '+data[0]+'\'s redak' );
    } );
} );
</script>