<script src="<?=APP::config('url') ?>public/assets/js/vendor.js"></script>
<script src="<?=APP::config('url') ?>public/assets/js/foundation.js"></script>
<script src="<?=APP::config('url') ?>public/app.js"></script>
<script src="https://kit.fontawesome.com/c867b674eb.js" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>

<script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
<!--<script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>-->
<script>
// tablice dodatne funkcije
$(document).ready(function() {
    var table = $('#example').DataTable(); 
} );
 //selektiranje
// $("tr").click(function(){
 //  $(this).addClass("selected").siblings().removeClass("selected");});

</script>