

<a float:right; class="button primary " href="<?=APP::config('url')?>kataforeza/novo"><i class="fas fa-address-card"></i><strong>Ulaz pozicija na bojanje</strong></a>
<a style = "float: right;" class="button success " href="<?=APP::config('url')?>kataforeza/obojano"><i class="fas fa-address-card"></i><strong>Izlaz pozicija s bojanja</strong></a>

<table id="example" class="display table table-bordered" style="width:100%">
        <thead style="background-color:black; color:white">
            <tr>
                <th>P</th>
                <th>Kataloški broj</th>
                <th>Naziv</th>
                <th>Takt</th>
                <th>Stanje</th>
                <th>Min obojat</th>
                <th>Lokacija</th>
                <th>Ulaz</th>
                <th>Izlaz</th>
                <th>Posalji</th>
                <th>Uredi</th> 
            </tr>
        </thead>
        <tbody>
            <?php foreach($kataforeze as $kataforeza): ?>
                <tr>
                    <?php if($kataforeza->prioritet==1):?> 
                        <td style="background-color:red; text-align:center;  font-weight: bold;">P<?=$kataforeza->prioritet?></td>
                    <?php elseif($kataforeza->prioritet==2):?> 
                        <td style="background-color:orange; text-align:center;">P<?=$kataforeza->prioritet?></td>
                    <?php else:?> 
                        <td style="text-align:center;">P<?=$kataforeza->prioritet?></td>
                    <?php endif;?> 
                    <td><?=$kataforeza->partnumber?></td>
                    <td><?=$kataforeza->naziv?></td>
                    <td style="text-align:center;"><?=$kataforeza->takt?></td>
                    <td style="text-align:center;"><?=$kataforeza->stanje?></td>
                    <td style="text-align:center;"><?=$kataforeza->minobojat?></td>
                    <td style="text-align:center;"><?=$kataforeza->lokacija?></td>
                    <td style="text-align:center;"><?=$kataforeza->stiglo?></td>
                    <td style="text-align:center;"><?=$kataforeza->otislo?></td>
                    <td style="text-align:center;"><a href="<?=APP::config('url')?>kataforeza/obojano?id=<?=$kataforeza->id?>"><i class="fas fa-paint-roller fa-2x"></i></a></td>
                    <td>
                    <a href="<?=APP::config('url')?>kataforeza/promjena?id=<?=$kataforeza->id?>"><i class="fas fa-edit fa-2x"></i></a> 
                    <a onclick="return confirm ('Ova akcija će obrisat poziciju na bojanju, da li ste sigurni da želite nastavit?');" href="<?=APP::config('url')?>kataforeza/brisanje?id=<?=$kataforeza->id?>"><i class="fas fa-trash-alt" style="color:red"></i></a></td> 
                </tr>
            <?php endforeach;?>
        </tbody>
    </table>


