
    <form action="<?=APP::config('url')?>kataforeza/novo" method="POST">
        <h4 class="text-center">Prijava pozicije koja se šalje na bojanje</h4>
        <div class="grid-x grid-padding-x">
            <div class="cell large-4 medium-6 medium-offset-3 small-12 large-offset-4">
                <div class="cell large-12">
                    <label>Kataloški broj pozicije
                        <input type="text" name="partnumber" value="<?=$kataforeza->partnumber?>" />
                    </label>
                </div>
                <div class="cell large-12 medium-12">
                    <label>Broj komada
                        <input type="number" name="stanje" value="<?=$kataforeza->stanje?>" />
                    </label>
                </div>
                <div class="cell large-12 medium-12">
                    <label>Prioritet
                        <input type="number" name="prioritet" value="<?=$kataforeza->prioritet?>" />
                    </label>
                </div>
                <div class="cell large-12 medium-12">
                    <label>Minimalno obojat
                        <input type="number" name="minobojat" value="<?=$kataforeza->minobojat?>" />
                    </label>
                </div>
                <div class="cell large-12 medium-12">
                    <label>Lokacija
                        <input type="text" name="lokacija" value="<?=$kataforeza->lokacija?>" />
                    </label>
                </div>
                <div class="large-12 small-12 cell">

                    <?= $poruka ?>
                    <br>
                </div>
                <div class="large-6 small-6 cell">
                    <p><input type="submit" class="button expanded primary" value="Unos"></input></p>
                 </div>
                 <div class="large-6 small-6 cell">
                    <p><a href="<?=APP::config('url')?>kataforeza/index" class="button expanded alert">Odustani</a></p>
                </div>
            </div>
        </form>
        </div>

