
    <form action="<?=APP::config('url')?>kataforeza/promjena" method="POST">
        <h4 class="text-center">Promjena pozicije na bojanju <?=$kataforeza->partnumber?>.</h4>
        <div class="grid-x grid-padding-x">
            <div class="cell large-4 medium-6 medium-offset-3 small-12 large-offset-4">
                <div class="cell large-12">
                    <label>Kataloški broj pozicije
                    <?php//greska ovdje partnumber  ne povlaci iz glavne tablice??>
                        <input type="text" name="glavnatablica" value="<?=$kataforeza->partnumber?>" />
                    </label>
                </div>
                <div class="cell large-12 medium-12">
                    <label>Broj komada
                        <input type="number" name="stanje" value="<?=$kataforeza->stanje?>" />
                    </label>
                </div>
                <div class="cell large-12 medium-12">
                    <label>Prioritet
                        <input type="number" name="prioritet" value="<?=$kataforeza->prioritet?>" />
                    </label>
                </div>
                <div class="cell large-12 medium-12">
                    <label>Minimalno obojat
                        <input type="number" name="minobojat" value="<?=$kataforeza->minobojat?>" />
                    </label>
                </div>
                <div class="cell large-12 medium-12">
                    <label>Lokacija
                        <input type="text" name="lokacija" value="<?=$kataforeza->lokacija?>" />
                    </label>
                </div>
                <div class="cell large-12 medium-12">
                    <label>Ulaz
                        <input type="text" name="stiglo" value="<?=$kataforeza->stiglo?>" />
                    </label>
                </div>
                <div class="cell large-12 medium-12">
                    <label>Izlaz
                        <input type="text" name="otislo" value="<?=$kataforeza->otislo?>" />
                    </label>
                </div>
                <div class="large-12 small-12 cell">
                <input type="hidden" name="id" value="<?=$kataforeza->id?>" />
                    <?= $poruka ?>
                    <br>
                </div>
                <div class="large-6 small-6 cell">
                    <p><input type="submit" class="button expanded primary" value="Unos"></input></p>
                 </div>
                 <div class="large-6 small-6 cell">
                    <p><a href="<?=APP::config('url')?>kataforeza/index" class="button expanded alert">Odustani</a></p>
                </div>
            </div>
        </form>
        </div>

