
        <form action="<?=APP::config('url')?>glavnatablica/novo" method="POST">
            <h4 class="text-center">Dodaj novu poziciju u bazu</h4>
            <div class="grid-x grid-padding-x">
                <div class="cell large-4">
                    <label>Kataloški broj
                        <input type="text" name="partnumber" value="<?=$glavnatablica->partnumber?>"/>
                    </label>
                </div>
                <div class="cell large-4">
                    <label>Naziv
                        <input type="text" name="naziv" value="<?=$glavnatablica->naziv?>"/>
                    </label>
                </div>
                <div class="cell large-4">
                    <label>Stanje
                        <input type="number" name="stanje" value="<?=$glavnatablica->stanje?>"/>
                    </label>
                </div>
                <div class="cell large-3 medium-3">
                    <label>Lokacija
                        <input type="text" name="lokacija" value="<?=$glavnatablica->lokacija?>"/>
                    </label>
                </div>
                <div class="cell large-3">
                    <label>Status
                        
                        <select name="status" value="<?=$glavnatablica->status?>">
                        <option <?php if ($glavnatablica->status==0){
                            echo 'selected="selected"';
                        } ?> value="0">Odaberite status</option>
                        <?php foreach($statusi as $status): ?>
                            <option <?php if ($glavnatablica->status==$status->id){
                            echo 'selected="selected"';
                        }?> value="<?=$status->id?>"><?=$status->naziv?></option>

                        <?php endforeach; ?>
                        </select>
                    </label>
                </div>
                <div class="cell large-3 medium-3">
                    <label>Tehnologija
                        <input type="text" name="tehnologija" value="<?=$glavnatablica->tehnologija?>"/>
                    </label>
                </div>
                <div class="cell large-3 medium-3">
                    <label>Takt
                        <input type="text" name="takt" value="<?=$glavnatablica->takt?>"/>
                    </label>
                </div>
                <div class="large-12 small-12 cell">
                    <label>Opis
                        <textarea name="opis" cols="50" rows="10" value="<?=$glavnatablica->opis?>"> </textarea>
                    </label>
                    <?= $poruka ?>
                    <br>
                </div>
                <div class="large-6 small-6 cell">
                    <p><input type="submit" class="button expanded primary" value="Unos"></input></p>
                 </div>
                <div class="large-6 small-6 cell">
                    <p><a href="<?=APP::config('url')?>glavnatablica/index" class="button expanded alert">Odustani</a></p>
                </div>
            </div>
        </form>


