<br>
            <div class="grid-x grid-padding-x">

                <div class="cell large-12">
                    <figure class="highcharts-figure">
                        <div id="graf2"></div>
                        <p class="highcharts-description">
                            Prikaz analize pozicija na tehnologiji kataforeza.
                        </p>
                    </figure>
                </div>
            </div>

<script>
function graf2funkcija(){
    Highcharts.chart('graf2', {
    chart: {
        plotBackgroundColor: null,
        plotBorderWidth: null,
        plotShadow: false,
        type: 'pie'
    },
    title: {
        text: 'Usporedba prioriteta i ukupno na kataforezi'
    },
    tooltip: {
        pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
    },
    accessibility: {
        point: {
            valueSuffix: '%'
        }
    },
    plotOptions: {
        pie: {
            allowPointSelect: true,
            cursor: 'pointer',
            dataLabels: {
                enabled: true,
                format: '<b>{point.name}</b>: {point.y} ({point.percentage:.1f}) %'
            }
        }
    },
    series: [{
        name: 'Brands',
        colorByPoint: true,
        data: [
            {name: 'Ukupno', y: <?php echo $dijagramUkupno[0]->ukupno?>},
            {name: 'Prioritet', y: <?php echo $dijagramUkupno[1]->ukupno?>}
        ]
    }]
});
}



</script>