
Nadzorna ploča <br>
*Htjeo bih printat tiket prilikom unosa podataka na kataforezu.
<br>
1. Kontrola stanja ne radi na kataforezi stanje manje od pokušaja knjiženja
<br>
            <div class="grid-x grid-padding-x">
                <div class="cell large-6">
                    <figure class="highcharts-figure">
                        <div id="graf1"></div>
                        <p class="highcharts-description">
                            Prikaz analize na tehnologiji kataforeza.
                        </p>
                    </figure>
                </div>
                <div class="cell large-6">
                    <figure class="highcharts-figure">
                        <div id="graf2"></div>
                        <p class="highcharts-description">
                            Prikaz analize ulaza izlaza pozicija na tehnologiji kataforeza.
                        </p>
                    </figure>
                </div>
            </div>


