
Nadzorna ploča <br>
Odaberite izbornik => baza => radnici   (to je bio moj ljetni rad)
<br>
Ili evo prečac <a href="<?=APP::config('url') ?>radnik/index">Radnici tablica</a>
<br>
prečac do kataforeza : <a href="<?=APP::config('url') ?>kataforeza/index">Kataforeza (novo)</a>
<br>
Problemi
<br>
1. Ne znam kako proknjizit broj na osnovu partnumbera u tablici kataforeza (da unesem cijeli broj a da se unese kljuc)
<br>
2. Ne znam kako dohvatit podatke iz baze (stanje pozicije te odradit update where id = id stanje=stanjeStaro + stanjeNovo).
<br>
