

<center><a class="button secondary expanded" href="<?=APP::config('url')?>radnik/novo"><i class="fas fa-address-card"></i><strong> Dodaj novog radnika</strong></a></center>

<table id="example" class="display table table-bordered" style="width:100%">
        <thead style="background-color:black; color:white">
            <tr>
                <th>Ime</th>
                <th>Prezime</th>
                <th>Email</th>
                <th>Radno mjesto</th>
                <th>Komentar</th>
                <th>Datum</th>
                <th>Uredi</th> 
            </tr>
        </thead>
        <tbody>
            <?php foreach($radnici as $radnik): ?>
                <tr>
                    <td><?=$radnik->ime?></td>
                    <td><?=$radnik->prezime?></td>
                    <td><?=$radnik->email?></td>
                    <td><?=$radnik->radnomjesto?></td>
                    <td><?=$radnik->komentar?></td>
                    <td><?=$radnik->datum?></td>
                    <td><a href="<?=APP::config('url')?>radnik/promjena?id=<?=$radnik->id?>"><i class="fas fa-edit fa-2x"></i></a>
                     <?php if($radnik->povijestkretanjanaloga==0): ?>
                    <a onclick="return confirm ('Ova akcija će obrisat radnika, da li ste sigurni da želite nastavit?');" 
                    href="<?=APP::config('url')?>radnik/brisanje?id=<?=$radnik->id?>"><i class="fas fa-trash-alt" style="color:red"></i></a>
                    </td>
                     <?php endif;?>
                </tr>

            <?php endforeach;?>
        </tbody>
    </table>

