<center><a class="button secondary" href="#"><i class="fas fa-address-card"></i><strong> Dodaj novog radnika</strong></a></center>
<table id="example" class="display table table-bordered" style="width:100%">
        <thead class="thead-dark">
            <tr>
                <th>Ime</th>
                <th>Prezime</th>
                <th>Email</th>
                <th>Lozinka</th>
                <th>Radno mjesto</th>
                <th>Komentar</th>
                <th>Datum</th>
                <th>Uredi</th> 
            </tr>
        </thead>
        <tbody>
            <?php foreach($radnici as $radnik): ?>
                <tr>
                    <td><?=$radnik->ime?></td>
                    <td><?=$radnik->prezime?></td>
                    <td><?=$radnik->email?></td>
                    <td><?=$radnik->lozinka?></td>
                    <td><?=$radnik->radnomjesto?></td>
                    <td><?=$radnik->komentar?></td>
                    <td><?=$radnik->datum?></td>
                    <td><a href="#"><i class="fas fa-edit fa-2x"></i> </a>
                    <a href="#"><i class="fas fa-trash-alt" style="color:red"></i></a></td>
                </tr>

            <?php endforeach;?>
        </tbody>
    </table>