
        <form action="<?=APP::config('url')?>radnik/novo" method="POST">
            <h4 class="text-center">Dodaj novog radnika</h4>
            <div class="grid-x grid-padding-x">
                <div class="cell large-4">
                    <label>Ime
                        <input type="text" name="ime">
                    </label>
                </div>
                <div class="cell large-4">
                    <label>Prezime
                        <input type="text" name="prezime">
                    </label>
                </div>
                <div class="cell large-4">
                    <label>Radno mjesto
                        <input type="text" name="radnomjesto">
                    </label>
                </div>
                <div class="cell large-6 medium-6">
                    <label>Email
                        <input type="email" name="email">
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Lozinka
                        <input type="password" name="lozinka">
                    </label>
                </div>
        
                <div class="large-12 small-12 cell">
                    <label>Komentar
                        <textarea name="komentar" cols="50" rows="10"></textarea>
                    </label>
                    <?= $poruka ?>
                    <br>
                </div>
                <div class="large-6 small-6 cell">
                    <p><input type="submit" class="button expanded primary" value="Unos"></input></p>
                 </div>
                <div class="large-6 small-6 cell">
                    <p><a href="<?=APP::config('url')?>radnik/index" class="button expanded alert">Odustani</a></p>
                </div>
    
                </div>
            </div>
        </form>


