
        <form action="<?=APP::config('url')?>radnik/promjena" method="POST">
            <h4 class="text-center">Promjeni postoječeg radnika</h4>
            <div class="grid-x grid-padding-x">
                <div class="cell large-4">
                    <label>Ime
                        <input type="text" name="ime" value="<?=$radnik->ime?>"/>
                    </label>
                </div>
                <div class="cell large-4">
                    <label>Prezime
                        <input type="text" name="prezime" value="<?=$radnik->prezime?>"/>
                    </label>
                </div>
                <div class="cell large-4">
                    <label>Radno mjesto
                        <input type="text" name="radnomjesto" value="<?=$radnik->radnomjesto?>"/>
                    </label>
                </div>
                <div class="cell large-6 medium-6">
                    <label>Email
                        <input type="email" name="email" value="<?=$radnik->email?>"/>
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Lozinka
                        <input type="password" name="lozinka" value="<?=$radnik->lozinka?>"/>
                    </label>
                </div>
        
                <div class="large-12 small-12 cell">
                    <label>Komentar
                        <textarea name="komentar" cols="50" rows="10" ><?=$radnik->komentar?> </textarea>
                    </label>

                    <input type="hidden" name="id" value="<?=$radnik->id?>" />
                    
                    <?= $poruka ?>
                    <br>
                </div>
                <div class="large-6 small-6 cell">
                    <p><input type="submit" class="button expanded primary" value="Promjeni radnika"></input></p>
                 </div>
                <div class="large-6 small-6 cell">
                    <p><a href="<?=APP::config('url')?>radnik/index" class="button expanded alert">Odustani</a></p>
                </div>
            </div>
        </form>


