<div class="grid-x">
    <div class="cell large-4 medium-6 medium-offset-3 small-12 large-offset-4">
        <form class="log-in-form" action="<?=APP::config('url')?>index/autorizacija" method="POST">
        <h4 class="text-center">Prijava</h4>
        <label>Email
            <input type="email" name="email" placeholder="ivan@sdfgroup.com" value="<?=$email ?>">
        </label>
        <label>Lozinka
            <input type="password" name="lozinka" placeholder="Lozinka">
        </label>
        <p><input type="submit" class="button expanded" value="Prijavi se"></input></p>
        <?= $poruka ?>
        </form>
    </div>
</div>
