Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent fermentum ligula quis condimentum mattis. Ut id lobortis turpis. Donec tincidunt dignissim viverra. Ut fermentum ligula eget urna maximus venenatis. Suspendisse vulputate nunc sit amet velit dictum volutpat. Curabitur molestie accumsan diam in varius. Phasellus porta porttitor finibus. Integer tristique lobortis leo vitae auctor. Nunc finibus lacus efficitur diam vestibulum sollicitudin. Morbi suscipit fermentum neque sed venenatis. Maecenas eleifend vehicula 

<div style="text-align:center;">
<img src="https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/nature-quotes-1557340276.jpg?crop=1.00xw:0.757xh;0,0.0958xh&resize=980:*" alt="cetered image">
</div>