<div style="min-height:400px;">
    <div style="width:100%; text-align: center;">
    <button class="button success"   onclick="disbleMute()" type="button">Upali zvuk</button> 
     <button class="button alert"  onclick="enableMute()" type="button">Ugasi zvuk</button>  
    <video id="vfigger" poster="img/01.jpg" width="100%" height="100%" autoplay muted loop>
                 <source src="<?=APP::config('url') ?>public/img/video.mp4" type="video/mp4">
    </video>


   
    <script>
          var vid = document.getElementById("vfigger");
          function enableMute() {

              vid.muted = true;
          }
          function disbleMute() {

              vid.muted = false;
          }
          </script>

    </div>
</div>


